import {BabyImageBinary} from "../../storage/csvs/image/BabyImageBinary";
import {AppDataAdmZipCreator} from "../../storage/AppDataAdmZipCreator";
import {BabyCsv} from "../../storage/csvs/BabyCsv";
import {BabyDateOfBirthCsv} from "../../storage/csvs/BabyDateOfBirthCsv";
import {BabyImageCsv} from "../../storage/csvs/BabyImageCsv";
import {ExcretionCsv} from "../../storage/csvs/ExcretionCsv";
import {ExcretionNotificationTriggerCsv} from "../../storage/csvs/ExcretionNotificationTriggerCsv";
import {ExcretionTimeOfDayNotificationTriggerCsv} from "../../storage/csvs/ExcretionTimeOfDayNotificationTriggerCsv";
import {FeedCsv} from "../../storage/csvs/FeedCsv";
import {FeedingNotificationTriggerCsv} from "../../storage/csvs/FeedingNotificationTriggerCsv";
import {FeedingTimeOfDayNotificationTriggerCsv} from "../../storage/csvs/FeedingTimeOfDayNotificationTriggerCsv";
import {GeneralNotesNotificationTriggerCsv} from "../../storage/csvs/GeneralNotesNotificationTriggerCsv";
import {GeneralNotesTimeOfDayNotificationTriggerCsv} from "../../storage/csvs/GeneralNotesTimeOfDayNotificationTriggerCsv";
import {GrowthCsv} from "../../storage/csvs/GrowthCsv";
import {JournalEntryCsv} from "../../storage/csvs/JournalEntryCsv";
import {MedicationRecordsNotificationTriggerCsv} from "../../storage/csvs/MedicationRecordsNotificationTriggerCsv";
import {MedicationRecordsTimeOfDayNotificationTriggerCsv} from "../../storage/csvs/MedicationRecordsTimeOfDayNotificationTriggerCsv";
import {MedicineCsv} from "../../storage/csvs/MedicineCsv";
import {MedicineRecordCsv} from "../../storage/csvs/MedicineRecordCsv";
import {PauseCsv} from "../../storage/csvs/PauseCsv";
import {PumpingCsv} from "../../storage/csvs/PumpingCsv";
import {PumpingNotificationTriggerCsv} from "../../storage/csvs/PumpingNotificationTriggerCsv";
import {PumpingTimeOfDayNotificationTriggerCsv} from "../../storage/csvs/PumpingTimeOfDayNotificationTriggerCsv";
import {SleepCsv} from "../../storage/csvs/SleepCsv";
import {SleepingNotificationTriggerCsv} from "../../storage/csvs/SleepingNotificationTriggerCsv";
import {SleepingsTimeOfDayNotificationTriggerCsv} from "../../storage/csvs/SleepingsTimeOfDayNotificationTriggerCsv";
import {SyncDeviceIdCsv} from "../../storage/csvs/SyncDeviceIdCsv";
import {TeethCsv} from "../../storage/csvs/TeethCsv";
import {TemperatureCsv} from "../../storage/csvs/TemperatureCsv";
import {VaccinationCsv} from "../../storage/csvs/VaccinationCsv";

export const defaultAppDataZipCreator = (): AppDataAdmZipCreator => {
    const creator = new AppDataAdmZipCreator();

    creator.addFileSaver(BabyCsv.create(), (data => data.babies));
    creator.addFileSaver(BabyDateOfBirthCsv.create(), (data => data.babyDateOfBirth));
    creator.addFileSaver(BabyImageCsv.create(), (data => data.babyImages));
    creator.addFileSaver(ExcretionNotificationTriggerCsv.create(), (data => data.excretionNotificationTriggers));
    creator.addFileSaver(PumpingCsv.create(), (data => data.pumpings));
    creator.addFileSaver(PumpingNotificationTriggerCsv.create(), (data => data.pumpingNotificationTriggers));
    creator.addFileSaver(PumpingTimeOfDayNotificationTriggerCsv.create(), (data => data.pumpingTimeOfDayNotificationTriggers));
    creator.addFileSaver(SleepCsv.create(), (data => data.sleeps));
    creator.addFileSaver(SleepingNotificationTriggerCsv.create(), (data => data.sleepingNotificationTriggers));
    creator.addFileSaver(TeethCsv.create(), (data => data.teeths));
    creator.addFileSaver(TemperatureCsv.create(), (data => data.temperatures));
    creator.addFileSaver(VaccinationCsv.create(), (data => data.vaccinations));
    creator.addFileSaver(JournalEntryCsv.create(), (data => data.journalEntries));
    creator.addFileSaver(FeedCsv.create(), (data => data.feeds));
    creator.addFileSaver(ExcretionCsv.create(), (data => data.excretions));
    creator.addFileSaver(MedicineCsv.create(), (data => data.medicines));
    creator.addFileSaver(PauseCsv.create(), (data => data.pauses));
    creator.addFileSaver(GrowthCsv.create(), (data => data.growths));
    creator.addFileSaver(SleepingsTimeOfDayNotificationTriggerCsv.create(), (data => data.sleepingsTimeOfDayNotificationTriggers));
    creator.addFileSaver(MedicineRecordCsv.create(), (data => data.medicineRecords));
    creator.addFileSaver(ExcretionTimeOfDayNotificationTriggerCsv.create(), (data => data.excretionTimeOfDayNotificationTriggers));
    creator.addFileSaver(FeedingNotificationTriggerCsv.create(), (data => data.feedingNotificationTriggers));
    creator.addFileSaver(FeedingTimeOfDayNotificationTriggerCsv.create(), (data => data.feedingTimeOfDayNotificationTriggers));
    creator.addFileSaver(GeneralNotesNotificationTriggerCsv.create(), (data => data.generalNotesNotificationTriggers));
    creator.addFileSaver(GeneralNotesTimeOfDayNotificationTriggerCsv.create(), (data => data.generalNotesTimeOfDayNotificationTriggers));
    creator.addFileSaver(MedicationRecordsNotificationTriggerCsv.create(), (data => data.medicationRecordsNotificationTriggers));
    creator.addFileSaver(MedicationRecordsTimeOfDayNotificationTriggerCsv.create(), (data => data.medicationRecordsTimeOfDayNotificationTriggers));
    creator.addFileSaver(new SyncDeviceIdCsv(), (_ => _));
    creator.addFileSaver(new BabyImageBinary(), (_ => _));

    return creator;
};
